name: Python calculator tests

on:
  push:
    branches:
      - main
      - test-and-release-automation
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Python tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest \
          --html=reports/test-report.html \
          --self-contained-html \
          --junitxml=reports/test-results.xml

      - name: Parse test results
        id: parse_results
        if: always()
        run: |
          # echo "$GITHUB_STEP_SUMMARY"
          cat $GITHUB_STEP_SUMMARY
          python scripts/parse_results.py
          # cat $GITHUB_STEP_SUMMARY

      - name: Display test results
        if: always()
        run: |
          echo "Total Tests: ${{ steps.parse_results.outputs.total }}"
          echo "Passed Tests: ${{ steps.parse_results.outputs.passed }}"
          echo "Failed Tests: ${{ steps.parse_results.outputs.failed }}"
          echo "Skipped Tests: ${{ steps.parse_results.outputs.skipped }}"

      - name: Test passed
      # by default github actions consider the if condition with implicit success()
      # that's why we are using always() to ensure that this step runs regardless of the previous steps' success or failure.
        if: ${{ always() && steps.parse_results.outputs.failed == '0' }}
        run: echo "All test passed . Safe to continue with the workflow."

      - name : Test failed
        if: ${{ always() && steps.parse_results.outputs.failed != '0' }}
        run: echo "Some tests failed. Please check the test report for details."

      # - name: Create test summary
      #   #github step summary is a special file that GitHub Actions uses to display information about the workflow run in the GitHub UI inside summary section.
      #   #if: always() ensures that this step runs even if the previous steps fail, allowing you to capture test results and provide a summary regardless of the outcome of the tests.
      #   #continue-on-error: is not used here because we want the workflow to fail if the tests fail, but we still want to generate a summary and upload artifacts.
      #   if: always()
      #   run: |
      #     echo "##  Test summary:  ##" >> $GITHUB_STEP_SUMMARY
      #     echo "  " >> $GITHUB_STEP_SUMMARY
      #     echo "Test execution completed. Test report is available in the artifacts." >> $GITHUB_STEP_SUMMARY
      #     echo "  " >> $GITHUB_STEP_SUMMARY
      #     echo "Test report: \`test-report.html\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload test results to artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: reports/
          # archive: false

